### Set Webhook URL
POST https://api.telegram.org/bot{{token}}/setWebhook
Content-Type: application/json

{
  "url": "{{host}}/{{token}}"
}

### Get Webhook URL
GET https://api.telegram.org/bot{{token}}/getWebhookInfo
